### ISSUE TITLE
Update Roadmap with [Spark/Meridian] Milestones

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#14]
```[tasklist]
### Tasks
- [ ] Spark path to lab week
- [ ] Spark longer-term path to decentralization
- [ ] Spark Presentation / deliverable for FilDev
```

**Comment by MF416** [comment]
This seems done from the title, but merged with presentations / several other action items?

**Comment by coreymjames** [comment]
Pulled out incomplete tasks into separate issues 👍
