### ISSUE TITLE
Interview: Saturn Web3 CDN

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#2]
```[tasklist]
### Tasks
- [x] Schedule chat with Alex
- [ ] Have chat with Alex
- [ ] Add notes doc [here](https://www.notion.so/pl-strflt/S-S-M-User-Interviews-16238e86af3d448280691d5c8fd1ae92)
```

**Comment by juliangruber** [comment]
@coreymjames can you please share results from this?
