### ISSUE TITLE
Clarity on IPC Subnet next steps

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#36]
```[tasklist]
### Tasks
- [ ] Deploy IE contract to ipc subnet
- [ ] Point services at ipc subnet contract
- [ ] Point telemetry at ipc subnet contract
- [ ] Figure out user story for moving FIL from subnet to mainnet
```

**Comment by juliangruber** [comment]
I've added the technical issues as I currently see them

**Comment by coreymjames** [comment]
@MF416 this is marked 'done.'

The main outcome is that @juliangruber is aware of ~likelihood of IPC dependency coming through on our necessary timeline.

As long as that has been communicated, we're good. I am marking as closed, but please un-open if it is not.

**Comment by MF416** [comment]
This is broader than just timelines --> ties in with the PRD to ensure we have a few critical features in place for IPC so that Meridian can function

**Comment by coreymjames** [comment]
@MF416 should this be moved out of 'done' then as well?
